const jsonUser = {
  password: 'adminadmin',
  password_confirmation: 'adminadmin',
  nick: 'Sample Ivan',
  member_type: 'owner',
  is_adv_agree: true,
  time_zone: 'Asia/Yekaterinburg',
  admin_user_setting: {
    is_hide_history_applicant: true,
    is_hide_experience: true,
    is_hide_education: true,
    is_hide_chat: false,
    pick_sort_vacancies: 'owners',
    pick_sort_applications: 'table',
    download_pdf: {
      is_first_name: true,
      is_last_name: true,
      is_middle_name: true,
      is_photo: true,
      is_gender: true,
      is_birthday: true,
      is_age: true,
      is_country: true,
      is_citizenship: true,
      is_company: true,
      is_position: true,
      is_phone: true,
      is_email: true,
      is_tg: true,
      is_skype: true,
      is_money: true,
      is_total_experience: true,
      is_source_add: true,
      is_source_name: true,
      is_about_me: true,
      is_skills: true,
      is_vacancies: true,
      is_worklog: true,
      is_experience: true,
      is_education: true,
      is_contacts: true,
      is_tags: true,
      is_unidentified_info: true,
      is_resume_urls: true,
    },
  },
}

export { jsonUser }
